# Generated by Django 4.1.3 on 2023-10-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_mycustomuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
