# Generated by Django 4.1.3 on 2023-12-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_mycustomuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
