# Generated by Django 4.1.3 on 2023-06-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characters',
            field=models.TextField(null=True),
        ),
    ]
