# Generated by Django 4.1.3 on 2023-06-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_product_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photot',
            field=models.ImageField(upload_to='media'),
        ),
    ]
