# Generated by Django 4.1.3 on 2023-06-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_photos_photot'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_with_discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
