# Generated by Django 4.1.3 on 2023-07-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_product_price_with_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
