# Generated by Django 4.1.3 on 2023-07-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_category_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='session_key',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='productinfavourite',
            name='session_key',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
