# Generated by Django 4.1.3 on 2023-10-15 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prodcut_in_basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.productinbasket'),
        ),
    ]
