# Generated by Django 4.1.3 on 2023-10-15 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_order_prodcut_in_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='prodcut_in_basket',
        ),
        migrations.AddField(
            model_name='productinbasket',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.order'),
        ),
    ]
