# Generated by Django 4.1.3 on 2023-12-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_product_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_prespense',
            field=models.BooleanField(null=True),
        ),
    ]
